### ISSUE TITLE
Use ASAN versions of lavapipe in Unit Tests

### ISSUE THREAD

**Issue by darksylinc** [godotengine/godot-proposals#7452]
### Describe the project you are working on

None

### Describe the problem or limitation you are having in your project

I just saw a PR whose Unit Tests failed with the following useless info:

```

Run details

🐧 Linux / Editor with doubles and GCC sanitizers (target=editor, tests=yes, dev_build=yes, scu_build=yes, precision=double, use_asan=yes, use_ubsan=yes, linker=gold)
failed Aug 5, 2023 in 1h 0m 38s
2s
11s
37s
54s
1s
5s
0s
0s
51m 58s
0s
0s
0s
0s
11s
1m 56s
0s
0s
4m 36s
    #0 0x7f781018440f in __interceptor_free ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:122
    #1 0x7f77f54948fc  (/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so+0x2638fc)
    #2 0x7f77f5494b84  (/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so+0x263b84)
    #3 0x7f77f5473e78  (/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so+0x242e78)
    #4 0x7f77f5294e53  (/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so+0x63e53)
    #5 0x7f7800778f91  (/lib/x86_64-linux-gnu/libvulkan.so.1+0x24f91)
    #6 0x7f78007840a9 in vkDestroyDevice (/lib/x86_64-linux-gnu/libvulkan.so.1+0x300a9)
    #7 0x55c269582050 in VulkanContext::~VulkanContext() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x3b238050)
    #8 0x55c25fa4a7ff in VulkanContextX11::~VulkanContextX11() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x317007ff)
    #9 0x55c25f99880d in void memdelete<VulkanContextX11>(VulkanContextX11*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x3164e80d)
    #10 0x55c25f94c36a in DisplayServerX11::~DisplayServerX11() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x3160236a)
    #11 0x55c25fb2f0d7 in void memdelete<DisplayServer>(DisplayServer*) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x317e50d7)
    #12 0x55c25faa09fe in finalize_display() (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x317569fe)
    #13 0x55c25fb0c0df in Main::cleanup(bool) (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x317c20df)
    #14 0x55c25f8229a9 in main (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x314d89a9)
    #15 0x7f780f3c4082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)
    #16 0x55c25f82236d in _start (/home/runner/work/godot/godot/bin/godot.linuxbsd.editor.dev.double.x86_64.san+0x314d836d)

0x604000e2ff10 is located 0 bytes inside of 48-byte region [0x604000e2ff10,0x604000e2ff40)

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (41cfabdb8015b53ca921c4c64fa79e4edf226220)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(+0x314d9104) [0x55c25f823104] (??:?)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f780f3e3090] (??:0)
[3] /lib/x86_64-linux-gnu/libasan.so.5(+0x11b913) [0x7f7810192913] (??:0)
[4] /lib/x86_64-linux-gnu/libasan.so.5(+0x2f03a) [0x7f78100a603a] (??:0)
[5] /lib/x86_64-linux-gnu/libasan.so.5(+0x2ff34) [0x7f78100a6f34] (??:0)
[6] /lib/x86_64-linux-gnu/libasan.so.5(+0x11774e) [0x7f781018e74e] (??:0)
[7] /lib/x86_64-linux-gnu/libasan.so.5(+0x115935) [0x7f781018c935] (??:0)
[8] /lib/x86_64-linux-gnu/libasan.so.5(__interceptor_free+0xa9) [0x7f78101843d9] (??:0)
[9] /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so(+0x2638fd) [0x7f77f54948fd] (??:0)
[10] /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so(+0x263b85) [0x7f77f5494b85] (??:0)
[11] /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so(+0x242e79) [0x7f77f5473e79] (??:0)
[12] /usr/lib/x86_64-linux-gnu/libvulkan_lvp.so(+0x63e54) [0x7f77f5294e54] (??:0)
[13] /lib/x86_64-linux-gnu/libvulkan.so.1(+0x24f92) [0x7f7800778f92] (??:0)
[14] /lib/x86_64-linux-gnu/libvulkan.so.1(vkDestroyDevice+0x3a) [0x7f78007840aa] (??:0)
[15] VulkanContext::~VulkanContext() (??:?)
[16] VulkanContextX11::~VulkanContextX11() (??:?)
[17] void memdelete<VulkanContextX11>(VulkanContextX11*) (??:?)
[18] DisplayServerX11::~DisplayServerX11() (??:?)
[19] void memdelete<DisplayServer>(DisplayServer*) (??:?)
[20] finalize_display() (??:?)
[21] Main::cleanup(bool) (??:?)
[22] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(main+0x581) [0x55c25f8229aa] (??:?)
[23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f780f3c4083] (??:0)
[24] ./bin/godot.linuxbsd.editor.dev.double.x86_64.san(_start+0x2e) [0x55c25f82236e] (??:?)
```

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

The idea is to build lavapipe ourselves with ASAN, and then zip it into a blob to be stored on some server.

Then the Unit Tests downloads the blob and installs the custom lavapipe in order to get much more detailed information (note: this may make the unit tests take longer, possibly causing increased costs if we're paying for Github Actions)

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

Making your custom ICDs is quite easy.

First we need to download mesa from git and compile it via meson. I'm not going to cover this on detail but arguments look kinda like this (actual arguments change between versions but it's a good starting point):

```bash
meson build/ -Dplatforms=x11,drm -Ddri-drivers= -Dgallium-drivers=radeonsi,swrast -Dgallium-extra-hud=true -Dgallium-vdpau=true -Dgallium-va=true --buildtype=debug --prefix /home/username/mesa_debug/build/usr`
```

Under `/home/username/mesa_debug/build/usr` we'll find the two most important files:

```
~/mesa_debug/build/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so
~/mesa_debug/build/usr/share/vulkan/icd.d/lvp_icd.x86_64.json
```

These files with their folder structure should be placed under `~/.local` and they should be recognized by the Vulkan loader.

See [Driver Discovery on Linux](https://vulkan.lunarg.com/doc/view/1.3.204.1/mac/LoaderDriverInterface.html#user-content-driver-discovery-on-linux).

If not, then we need root access to place the JSON file in `/usr/share/vulkan/icd.d`.
Note that the JSON file contains the path to where `libvulkan_lvp.so` is. It looks like this:

```json
{
    "ICD": {
        "api_version": "1.1.238",
        "library_path": "/usr/lib/x86_64-linux-gnu/libvulkan_lvp.so"
    },
    "file_format_version": "1.0.0"
}
```

With a custom built Lavapipe, we can get more information about what crashed and where; which can be used to trace back what's going wrong.

### If this enhancement will not be used often, can it be worked around with a few lines of script?

No.

But if this is too expensive, it can still be considered by the main dev team for running the unit tests locally.

### Is there a reason why this should be core and not an add-on in the asset library?

No.

**Comment by Calinou** [comment]
> possibly causing increased costs if we're paying for Github Actions)

We don't pay for CI, so it should be fine. The main question is where the ZIP should be stored. I guess we can have a dedicated repository with a single tag (+ GitHub Release) that stores the ZIP in question.
